server:
  applicationConnectors:
    # Comment below if you want HTTPS only (maybe for security?)
    - type: http
      port: 8281

    - type: https
      port: 8284
      keyStorePath: keystore.jks
      keyStorePassword: secret
      certAlias: jetty
      validateCerts: false
      validatePeers: false
      needClientAuth: false
      wantClientAuth: false
      
      
  adminConnectors:
    - type: http
      port: 8282

logging:
  level:  INFO  # default level off all loggers

  loggers:
    com.example:             DEBUG

  appenders:
    - type: console
      timeZone: UTC


# custom top-level config (this one also has a non-empty validator)
appName: My DiceRoll App

diceEngine:
    numDice: 4
    weights: [0.166667,0.166667,0.166667,0.166667,0.166667,0.166667]

# custom top-level section
swagger:
    host: localhost
    port: 8284